### ISSUE TITLE
Where to host a PHP script for my twitter bot?

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/Botnjak#1]
I know about hosting a nodejs twitter bot script on Heroku, but could I do the same with a PHP script?
Are there any other free solutions out there regarding this matter?

**Comment by Mickey0001** [comment]
[freescripthost.com](https://www.freescripthost.com/) maybe?

**Comment by TheAdnan** [comment]
@Mickey0001 I'll give it a shot!
