### ISSUE TITLE
phrases as keywords and @nickname in reply

### ISSUE THREAD

**Issue by 6p5ra** [TheAdnan/Botnjak#4]
Help me to add phrases as keywords instead of words.

And there is another bug .. I can not reply phrases containing @nickname

Can you add these features please. 

Sorry for my lang

**Comment by TheAdnan** [comment]
Can you post your code somewhere and I'll try to help as much as I can

**Comment by 6p5ra** [comment]
```
$query = array(
  'q' => 'bosanac OR bosanci OR bosancu OR bosanca OR bosancima OR bosance',
  'count' => '20',
  'result_type' => 'recent'
);
```

 I need

`'q' => 'some phrase 1 OR some phrase 2 OR some phrase 3 OR some phrase 4 OR some phrase 5 OR some phrase 6',`

`$newtweet = "bošnjak*";`

I need:

`$newtweet = "@username @username";`

I need to search for phrases instead of keywords.

**Comment by 6p5ra** [comment]
and can u add the retweet,follow and like futures with some timeouts? Because my first bot was banned for too frequent answers
